#include "launcher_theme.hxx"

namespace sf4e {
namespace launcher {

QString LauncherStylesheet() {
	return QStringLiteral(
		"QMainWindow, QWidget#centralWidget { background: #070809; color: #d8dce0; font-family: 'Segoe UI', Arial, sans-serif; font-size: 12px; }"
		"QLabel#eyebrow { color: #8b949e; font-size: 10px; font-weight: 700; letter-spacing: 1.2px; }"
		"QLabel#title { color: #f4f6f8; font-size: 18px; font-weight: 700; letter-spacing: -0.2px; }"
		"QLabel#subtitle { color: #9aa3ad; font-size: 11px; }"
		"QLabel#versionBadge { background: #12151a; color: #b4bcc4; border: 1px solid #2a3138; padding: 3px 7px; border-radius: 5px; font-size: 11px; font-weight: 600; }"
		"QLabel#warningBanner { background: #16130c; color: #e0c980; border: 1px solid #3a3220; padding: 6px 8px; border-radius: 5px; font-size: 11px; }"
		"QLabel#hint { color: #7d868f; font-size: 11px; }"
		"QLabel#connectionLine { color: #c5ccd3; font-weight: 600; font-size: 11px; padding: 0; }"
		"QLabel#connectionLine[statusKind=\"error\"] { color: #f0a0a0; }"
		"QLabel#connectionLine[statusKind=\"success\"] { color: #9fd4a4; }"
		"QLabel#toastLabel { background: #12151a; border: 1px solid #2a3138; padding: 8px 10px; border-radius: 6px; }"
		"QLabel#toastLabel[toastKind=\"error\"] { color: #f0a0a0; border-color: #5a3030; background: #1a1214; }"
		"QLabel#toastLabel[toastKind=\"success\"] { color: #9fd4a4; border-color: #2f4a34; background: #121a14; }"
		"QLabel#modeCardTitle { color: #f2f4f6; font-weight: 700; font-size: 14px; }"
		"QLabel#modeCardDesc { color: #8b949e; font-size: 11px; }"
		"QLabel#shareCardTitle { color: #8b949e; font-size: 10px; font-weight: 700; letter-spacing: 0.6px; text-transform: uppercase; }"
		"QLabel#shareCardValue { color: #f4f6f8; font-size: 14px; font-weight: 700; letter-spacing: 0.6px; }"
		"QLabel#updateStatus { color: #8b949e; font-size: 11px; padding: 2px 0; }"
		"QLabel#updateStatus[updateKind=\"success\"] { color: #c5d0c8; }"
		"QLabel#updateStatus[updateKind=\"error\"] { color: #f0a0a0; }"
		"QGroupBox { background: #0e1114; border: 1px solid #2a3138; border-radius: 8px; margin-top: 10px; font-weight: 700; }"
		"QGroupBox::title { subcontrol-origin: margin; left: 10px; padding: 0 6px; color: #c5ccd3; background: #070809; }"
		"QLineEdit, QSpinBox, QPlainTextEdit, QComboBox { background: #0a0c0e; color: #d8dce0; border: 1px solid #2a3138; border-radius: 6px; padding: 7px 10px; min-height: 30px; }"
		"QLineEdit:hover, QSpinBox:hover, QComboBox:hover { border-color: #3d454e; }"
		"QLineEdit:focus, QSpinBox:focus, QPlainTextEdit:focus, QComboBox:focus { border: 1px solid #d14a4a; }"
		"QLineEdit:disabled, QSpinBox:disabled, QComboBox:disabled { background: #08090b; color: #5a6169; border-color: #1f242a; }"
		"QLineEdit::placeholder { color: #5a6169; }"
		// Qt ships a light-on-light default for these two; unstyled they break
		// the dark theme badly wherever a list or scroll area appears.
		"QComboBox::drop-down { border: none; width: 18px; }"
		"QComboBox QAbstractItemView { background: #0e1114; color: #d8dce0; border: 1px solid #2a3138; selection-background-color: #1a1f26; selection-color: #f2f4f6; outline: none; }"
		"QToolTip { background: #12151a; color: #d8dce0; border: 1px solid #3d454e; padding: 5px 7px; border-radius: 4px; }"
		"QScrollBar:vertical { background: transparent; width: 10px; margin: 0; }"
		"QScrollBar::handle:vertical { background: #262c33; border-radius: 5px; min-height: 28px; }"
		"QScrollBar::handle:vertical:hover { background: #39414a; }"
		"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical { height: 0; border: none; }"
		"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical { background: transparent; }"
		"QScrollBar:horizontal { background: transparent; height: 10px; margin: 0; }"
		"QScrollBar::handle:horizontal { background: #262c33; border-radius: 5px; min-width: 28px; }"
		"QScrollBar::handle:horizontal:hover { background: #39414a; }"
		"QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal { width: 0; border: none; }"
		"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal { background: transparent; }"
		"QLineEdit#roomCodeInput { font-size: 15px; font-weight: 700; letter-spacing: 1px; padding: 6px 8px; min-height: 30px; border-radius: 6px; }"
		"QPushButton#primaryButton { background: #a03336; color: #fff5f5; border: 1px solid #b84447; padding: 10px 16px; font-weight: 700; border-radius: 6px; min-height: 34px; letter-spacing: 0.3px; }"
		"QPushButton#primaryButton:hover { background: #b84447; }"
		"QPushButton#primaryButton:pressed { background: #8c2b2e; }"
		"QPushButton#primaryButton:disabled { background: #3a2425; color: #8a7a7a; border-color: #2e2222; }"
		"QPushButton#secondaryButton { background: #12151a; color: #d8dce0; border: 1px solid #2a3138; padding: 7px 12px; border-radius: 6px; min-height: 30px; }"
		"QPushButton#secondaryButton:hover { border-color: #d14a4a; background: #181c22; }"
		"QPushButton#secondaryButton:pressed { background: #0d1013; }"
		"QPushButton#secondaryButton:disabled { color: #666; border-color: #23282e; }"
		// Confirmation state for Copy / Paste buttons: green reads as "done"
		// without the button jumping size, since the label stays a short word.
		"QPushButton#secondaryButton[copied=\"true\"] { color: #9fd4a4; border-color: #2f4a34; background: #121a14; }"
		"QPushButton#secondaryButton[copied=\"true\"]:hover { border-color: #3d5c43; background: #121a14; }"
		"QPushButton#stepperButton { background: #12151a; color: #d8dce0; border: 1px solid #2a3138; min-height: 30px; max-height: 30px; padding: 0; border-radius: 6px; font-size: 14px; font-weight: 700; }"
		"QPushButton#stepperButton:hover { border-color: #d14a4a; background: #181c22; }"
		"QPushButton#modeCardHost, QPushButton#modeCardJoin, QPushButton#modeCardOffline {"
		"  background: #101318; border: 1px solid #2f363d; border-left-width: 3px; text-align: left;"
		"  border-radius: 8px; min-height: 62px; max-height: 68px; padding: 2px; }"
		"QPushButton#modeCardHost { border-left-color: #d14a4a; }"
		"QPushButton#modeCardJoin { border-left-color: #5ecf8f; }"
		"QPushButton#modeCardOffline { border-left-color: #8b949e; }"
		"QPushButton#modeCardHost:hover, QPushButton#modeCardJoin:hover, QPushButton#modeCardOffline:hover {"
		"  background: #161a20; border-color: #4a545e; border-left-width: 3px; }"
		"QPushButton#modeCardHost:hover { border-left-color: #e85c5c; }"
		"QPushButton#modeCardJoin:hover { border-left-color: #7ae0a8; }"
		"QPushButton#modeCardOffline:hover { border-left-color: #b0b7be; }"
		"QPushButton#modeCardHost:pressed, QPushButton#modeCardJoin:pressed, QPushButton#modeCardOffline:pressed {"
		"  background: #1a1f26; border-color: #d14a4a; }"
		"QPushButton#segmentBtn { background: #0c0e11; color: #8b949e; border: 1px solid #2a3138; padding: 5px 12px; border-radius: 5px; }"
		"QPushButton#segmentBtn:checked { background: #161a20; color: #f2f4f6; border: 1px solid #4a545e; border-bottom: 2px solid #d14a4a; }"
		"QPushButton#segmentBtn:hover { border-color: #4a545e; }"
		// Reads as a control, not as another line of status text: it needs a
		// visible surface and a real hit target, but stays quieter than the
		// secondary buttons so it never competes with the page's main action.
		"QPushButton#backButton { background: #12151a; color: #c5ccd3; border: 1px solid #2a3138;"
		"  padding: 6px 14px; border-radius: 6px; min-height: 28px; text-align: center; font-weight: 600; }"
		"QPushButton#backButton:hover { background: #181c22; border-color: #d14a4a; color: #f2f4f6; }"
		"QPushButton#backButton:pressed { background: #0d1013; }"
		"QWidget#shareCard { background: #0e1114; border: 1px solid #2a3138; border-radius: 6px; }"
		"QWidget#shareCard[shareEmpty=\"true\"] { border-color: #23282e; }"
		"QWidget#shareCard[shareEmpty=\"true\"] QLabel#shareCardValue { color: #555; }"
		"QListWidget { background: #0a0c0e; border: 1px solid #2a3138; border-radius: 6px; }"
		"QListWidget::item { padding: 8px; border-bottom: 1px solid #1f252b; }"
		"QListWidget::item:selected { background: #161a20; color: #f2f4f6; }"
		"QScrollArea { border: none; background: transparent; }"
		"QPlainTextEdit { border-radius: 6px; }"
	);
}

} // namespace launcher
} // namespace sf4e
