#!/usr/bin/env python3
"""Writes src/platform/ReportUnicodeTables.hxx: the Unicode case folding and
word-character ranges that report redaction matches the player's names with
(platform/ProblemReport.cxx). The data is the running Python's own Unicode
database: str.casefold is Unicode full case folding (CaseFolding.txt status C
and F, without the Turkic T mappings), and a word character is any letter,
mark, number or connector punctuation. Run it with the Python whose Unicode
version the header should carry, then rebuild. The data is Unicode Character
Database data under the Unicode License V3 (src/platform/Unicode-License.txt),
which packages carry in notices/THIRD_PARTY_LICENSES.txt (collect-notices.py)."""

import sys
import unicodedata
from pathlib import Path

OUTPUT = Path(__file__).resolve().parents[1] / "src" / "platform" / "ReportUnicodeTables.hxx"


def folds():
    rows = []
    for point in range(0x110000):
        if 0xD800 <= point <= 0xDFFF:
            continue
        folded = chr(point).casefold()
        if folded != chr(point):
            if len(folded) > 3:
                sys.exit(f"U+{point:04X} folds to {len(folded)} characters; the table holds 3")
            rows.append((point, [ord(c) for c in folded]))
    return rows


def word_ranges():
    ranges = []
    for point in range(0x110000):
        word = unicodedata.category(chr(point))[0] in "LMN" or unicodedata.category(chr(point)) == "Pc"
        if not word:
            continue
        if ranges and ranges[-1][1] == point - 1:
            ranges[-1][1] = point
        else:
            ranges.append([point, point])
    return ranges


def main():
    lines = [
        "#pragma once",
        "// Generated by scripts/generate-report-unicode.py; do not edit.",
        f"// Derived from Unicode {unicodedata.unidata_version} data through CPython; see src/platform/Unicode-License.txt.",
        "// Folds: Unicode full case folding, one to three characters per point.",
        "// WordRanges: letters, marks, numbers and connector punctuation.",
        "namespace sf4e { namespace reports { namespace unicode {",
        f'inline constexpr char Version[] = "{unicodedata.unidata_version}";',
        "struct Fold { char32_t point; char32_t to[3]; };",
        "inline constexpr Fold Folds[] = {",
    ]
    rows = folds()
    for i in range(0, len(rows), 4):
        chunk = rows[i:i + 4]
        lines.append("    " + " ".join(
            "{0x%X,{%s}}," % (point, ",".join("0x%X" % c for c in (to + [0, 0])[:3])) for point, to in chunk))
    lines.append("};")
    lines.append("struct Range { char32_t first, last; };")
    lines.append("inline constexpr Range WordRanges[] = {")
    ranges = word_ranges()
    for i in range(0, len(ranges), 6):
        lines.append("    " + " ".join("{0x%X,0x%X}," % (a, b) for a, b in ranges[i:i + 6]))
    lines.append("};")
    lines.append("} } }")
    OUTPUT.write_bytes(("\r\n".join(lines) + "\r\n").encode("ascii"))
    print(f"{OUTPUT.name}: {len(rows)} folds, {len(ranges)} word ranges, Unicode {unicodedata.unidata_version}")


if __name__ == "__main__":
    main()
