# Embed original font bytes; running the mod never needs loose fonts or downloads.
set(sf4e_font_source "${CMAKE_CURRENT_SOURCE_DIR}/src/ui/fonts")
set(sf4e_font_header "#pragma once\nnamespace sf4e { namespace ui { namespace fonts {\n")
# Also used by sf4e_brand.cmake, which is included after this file.
function(sf4e_hex_bytes path out_var)
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${path}")
    file(READ "${path}" hex HEX)
    # Sixteen bytes per line keeps generated compiler input manageable.
    string(REGEX REPLACE "(................................)" "\\1\n" rows "${hex}")
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${rows}")
    set(${out_var} "${bytes}" PARENT_SCOPE)
endfunction()
function(sf4e_embed_font filename symbol expected_hash)
    set(font_path "${sf4e_font_source}/${filename}")
    file(SHA256 "${font_path}" font_hash)
    if(NOT font_hash STREQUAL expected_hash)
        message(FATAL_ERROR "Unexpected font content: ${filename}")
    endif()
    sf4e_hex_bytes("${font_path}" font_bytes)
    set(sf4e_font_header "${sf4e_font_header}alignas(4) static const unsigned char ${symbol}[] = {\n${font_bytes}\n};\n" PARENT_SCOPE)
endfunction()
sf4e_embed_font("Inter-Regular.ttf" Body "40d692fce188e4471e2b3cba937be967878f631ad3ebbbdcd587687c7ebe0c82")
sf4e_embed_font("Inter-SemiBold.ttf" Heading "78a843fade9d4612a5567302fb595b56976eb5fcebf4fea5a5912d638bafcde3")
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${sf4e_font_source}/OFL.txt")
file(READ "${sf4e_font_source}/OFL.txt" sf4e_font_license)
string(APPEND sf4e_font_header "static const char License[] = R\"InterOFL(${sf4e_font_license})InterOFL\";\n} } }\n")
file(GENERATE OUTPUT "${CMAKE_CURRENT_BINARY_DIR}/generated/EmbeddedFonts.hxx" CONTENT "${sf4e_font_header}")
target_include_directories(sf4e_ui PRIVATE "${CMAKE_CURRENT_BINARY_DIR}/generated")
